borg_passphrase: ENC[AES256_GCM,data:HAjSZGk9A5gRp9X5WFMChPjnzGh80aDDIR1Qf+t82tKlXMDFFzq74WsmxRAJ8w==,iv:FZk04e7xka1Kz9DK5cXC41QHVkI/yNO+/BFhojlKf2U=,tag:s5Es1YwkwxfbqoSZLcWNEA==,type:str]
sops:
    age:
        - recipient: age19497qrtggnh0wgp2mw5j9j4h2h05alrynus2wjd679ve2tl4pp0snd4mn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreWlsbnVnN0g0aG0xeU5w
            YjYrVHB4STQyM2ZpN3N2OVhveUVjekNMcWhvCi9Oc0dsWnBqUHR0TkNDZCswSm1q
            cUh0VUpzYVBCSW0xM0Ntb1Jkd2RPUUUKLS0tIEtFSFI3MC9HVHZ3cllsNE5DR25L
            ZzBJcUh4dUdmRXpXWHU0eUVRMWpWNDAK9nqKGclyHep28SXjdV7HnUAKwFcL03DR
            m23X5xKqxgNbSoUwNgXBdhIP4vCsl0EgVVfKc9rMvibihBrRoDf+9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-19T19:42:42Z"
    mac: ENC[AES256_GCM,data:BnpPeeoa0G8oy+xb1ou10FIc3Pw7Qt6/wzXF+f63BAkDuycJU9gjbmIG5uOjy+JB4KtSqQYavDZHQijCsiuC6g3GCCTtKSUzb4Al2+ZHi8YB6jOe6pTHdkW+grkYDWWrfJgXAMlkf+LQPBQ8WGysTxZ+Bsq6zTgEpcwssE52LBI=,iv:MixSn6UVmxbWZya3HYUkUPmPWi4Y0x5OnJPTVs+kLtU=,tag:/82jjJTi7YvrCdGq01XrMQ==,type:str]
    pgp:
        - created_at: "2025-04-19T19:42:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA21JjLrfOQa4ARAAwuoicl7bTVfMInr2ihRSwzgCGB3yXnqtqmfOubNKqzSZ
            /Tigczc35M0TxUIdxM4s457cDdMA4U0AExgW6puU2Wy8AdgOfPfmgwiJyF7PMBn3
            Prrxzqnw6Cy3K0gsD4JEZ9/+4+S0GKF9B6tbtl8MliFgisHQTL5B3xeutEKDchK2
            /QoI+fyWWgi5OIQVsPV9Zlz+dAS2mQOtegg0PbGwI/sBMF0Ew5rEyhGoYKRFsz1z
            ioR9Esd8fIVBcn8xSeqr1SJvVwbAaG9BCKZF9+U3jGevYwAgSH+iwBEVTP0hE0ff
            55kZBlPPtE1mcaMgxfbOTd/eglFAEEfSMU+8u8H+UpftxsqIV0QGTONoZFXjKTXR
            NT42yUI8wd/T+6a+0zaz21quiiF/26WZ8Fer8xQd46/0YimprtvmP3+bXSp8c+SV
            9wAZl/lg1ZUOcKFiHg+0qNwha/2Z8pb5GMt5DCRxRS1XuNRbdnajTm9Lpyqut9bs
            x73Lp4zIjOmskx14YkAR2K/lAdRfQYobNTP9rS/3Cvun0CNa1LFBX37sQ1fqeoXW
            TAYOEV3EHWUalv4s2DO1kZxfyR8EOIUftjUC8uBOS1BbBLizlS7AJCoA8P8PmKHW
            Wlgb0nQtUiiPoln39ywLsQt7eWgfDFVPAcH9n14c9W7ODaod06JS5mC9ETv0z7rS
            XgFaBcCOvs2K9sh3K6yUkpft5zHoviyxAxvqjFtpM7GU2qp/3iM4+E4Zjm0VISCM
            7HnidKhDuxuxrrV5xvT5OFT57e+xHroSNupb7J595KaWbt75C4MBpnDexOQi2CY=
            =WcIh
            -----END PGP MESSAGE-----
          fp: 67AA5B46E7AF78053167FE343B8F814A784218F8
    unencrypted_suffix: _unencrypted
    version: 3.10.1
